#!/usr/bin/bash
if [ $# == 1 ]; then
	if [ $1 == -h ]; then
		echo 'USAGE::'
		echo "	getshell <Name of Exec>"
	else
		objdump -M intel -D $1 | grep '[0-9a-f]:' | grep -v 'file' | cut -f2 -d: | cut -f1-7 -d' ' | tr -s ' ' | tr '\t' ' ' | sed 's/ $//g' | sed 's/ /\\\x/g' | paste -d '' -s
	fi
else
	echo 'USAGE::'
        echo "  getshell <Name of Exec>"
fi
